Feature/test form
peaksoft-school/canva-peaksoft-web pull request #20
Opened 2022-02-09 07:57 UTC by AlmazHecker

2022-02-14 16:49 UTC, zhumabek requested changes

2022-02-14 16:49 UTC, zhumabek commented on src/components/TestForm/TestFormContent.js
> +   // radio-button
удалить

2022-02-14 16:49 UTC, zhumabek commented on src/components/TestForm/TestFormContent.js
> +      const debounce = setTimeout(() => {
сделай хук useDebounce()

2022-02-14 16:49 UTC, zhumabek commented on src/components/TestForm/TestFormContent.js
> +   React.useEffect(() => setInputForm({ ...data }), [data.testName])
data = { testName: '' }
data.testName = 'rnfcjr'
react узнает что data изменился или нет ?

2022-02-14 16:49 UTC, zhumabek commented on src/components/TestForm/TestFormContent.js
> +   }, [inputForm.type])
тоже самое

2022-02-14 16:49 UTC, zhumabek commented on src/components/TestForm/TestFormContent.js
> +import React from 'react'
TesFormItem лучше звучит

2022-02-14 16:49 UTC, zhumabek commented on src/containers/TestForm.js
> +   console.log('component did update')
удалить

2022-02-14 16:49 UTC, zhumabek commented on src/containers/TestForm.js
> +         variants: question.variants.map((variant, index) => ({
сначала приготовь варианты потом передавай как значение
variants: variants

2022-02-14 16:49 UTC, zhumabek commented on src/containers/TestForm.js
> +   const testBlank = React.useCallback(
blankTestItem

2022-02-14 16:49 UTC, zhumabek commented on src/containers/TestForm.js
> +      console.log(testQuestions)
...
шо

2022-02-14 16:49 UTC, zhumabek commented on src/containers/TestForm.js
> +            sx={{
опять инлайн стили

2022-02-15 07:27 UTC, AlmazHecker commented on src/components/TestForm/TestFormContent.js
> +   React.useEffect(() => setInputForm({ ...data }), [data.testName])
узнает

2022-02-15 12:24 UTC, merged